name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install mypy ruff coverage
            - name: Type check
              run: mypy . || true
            - name: Lint
              run: ruff check . || true
            - name: Tests
              run: coverage run -m pytest -q
            - name: Coverage report
              run: coverage report -m || true
