name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install mypy black isort flake8
            - name: Type check
              run: mypy . || true
            - name: Lint (flake8)
              run: flake8 . || true
            - name: Format check (black)
              run: black --check . || true
            - name: Import sort check (isort)
              run: isort --check-only . || true
            - name: Tests
              run: pytest -q
