name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install tools
              run: |
                  python -m pip install --upgrade pip
                  pip install ruff mypy
            - name: Ruff lint
              run: ruff check . --output-format=github
            - name: Mypy type check
              run: mypy . --ignore-missing-imports
    build-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12", "3.13"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install mypy ruff coverage
            - name: Type check
              run: mypy .
            - name: Lint
              run: ruff check .
            - name: Tests
              run: coverage run -m pytest -q
            - name: Coverage report
              run: coverage report -m
