name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Version (e.g. 0.1.1)"
                required: true

jobs:
    build-publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"
            - name: Install build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine
            - name: Build
              run: python -m build
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist/*
            # Uncomment when PyPI publishing is desired and set secrets PYPI_API_TOKEN
            # - name: Publish to PyPI
            #   env:
            #     TWINE_USERNAME: __token__
            #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
            #   run: |
            #     twine upload dist/*
